services:
  - type: web
    name: disaster-management-backend
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
